# -*- coding:utf-8 -*-
sqlserver_meta = {
    "DEMO":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "CASEVERSION":"int",
        "I_F_CODE":"char(2)",
        "EVENT_DT":"char(10)",
        "MFR_DT":"char(10)",
        "INIT_FDA_DT":"char(10)",
        "FDA_DT":"char(10)",
        "REPT_COD":"char(4)",
        "AUTH_NUM":"",
        "MFR_NUM":"varchar(100)",
        "MFR_SNDR":"varchar(100)",
        "LIT_REF":"",
        "AGE":"real",
        "AGE_COD":"char(5)",
        "AGE_GRP":"",
        "AGE_TYPE":"int",
        "SEX":"char(5)",
        "E_SUB":"char(3)",
        "WT":"real",
        "WT_COD":"char(5)",
        "WT_KG":"float",
        "REPT_DT":"char(10)",
        "TO_MFR":"char(3)",
        "OCCP_COD":"char(5)",
        "REPORTER_COUNTRY":"varchar(30)",
        "OCCR_COUNTRY":"char(5)",
        "FOLL_SEQ":"varchar(10)",
        "IMAGE":"varchar(10)",
        "DEATH_DT":"varchar(10)",
        "CONFID":"varchar(10)"
    },
    "DRUG":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "DRUG_SEQ":"bigint",
        "ROLE_COD":"char(5)",
        "DRUGNAME":"varchar(500)",
        "PROD_AI":"",
        "VAL_VBM":"char(5)",
        "ROUTE_":"varchar(30)",
        "DOSE_VBM":"varchar(300)",
        "CUM_DOSE_CHR":"real",
        "CUM_DOSE_UNIT":"char(20)",
        "DECHAL":"char(5)",
        "RECHAL":"char(5)",
        "LOT_NUM":"varchar(300)",
        "EXP_DT":"varchar(100)",
        "NDA_NUM":"char(20)",
        "DOSE_AMT":"char(20)",
        "DOSE_UNIT":"char(20)",
        "DOSE_FORM":"varchar(50)",
        "DOSE_FREQ":"char(20)"
    },
    "REAC":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "PT":"varchar(100)",
        "DRUG_REC_ACT":""
    },
    "OUTC":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "OUTC_COD":"varchar(10)"
    },
    "RPSR":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "RPSR_COD":"varchar(10)"
    },
    "THER":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "DSG_DRUG_SEQ":"char(15)",
        "START_DT":"char(10)",
        "END_DT":"varchar(10)",
        "DUR":"varchar(10)",
        "DUR_COD":"char(5)",
    },
    "INDI":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "INDI_DRUG_SEQ":"bigint",
        "INDI_PT":"varchar(100)"
    }
}