# -*- coding:utf-8 -*-
ms_meta = {
    "DEMO":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "CASEVERSION":"int",
        "I_F_CODE":"char(1)",
        "EVENT_DT":"char(8)",
        "MFR_DT":"char(8)",
        "INIT_FDA_DT":"char(8)",
        "FDA_DT":"char(8)",
        "REPT_COD":"char(4)",
        "AUTH_NUM":"varchar(70)",
        "MFR_NUM":"varchar(100)",
        "MFR_SNDR":"varchar(100)",
        "LIT_REF":"varchar(550)",
        "AGE":"varchar(30)",
        "AGE_COD":"char(5)",
        "AGE_GRP":"char(1)",
        "AGE_TYPE":"int",
        "SEX":"char(5)",
        "GNDR_COD":"char(5)",
        "E_SUB":"char(3)",
        "WT":"varchar(10)",
        "WT_COD":"char(5)",
        "WT_KG":"float",
        "REPT_DT":"char(10)",
        "TO_MFR":"char(3)",
        "OCCP_COD":"char(5)",
        "REPORTER_COUNTRY":"varchar(50)",
        "OCCR_COUNTRY":"char(5)",
        "FOLL_SEQ":"varchar(10)",
        "IMAGE":"varchar(10)",
        "DEATH_DT":"varchar(10)",
        "CONFID":"varchar(10)"
    },
    "DRUG":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "DRUG_SEQ":"bigint",
        "ROLE_COD":"char(2)",
        "DRUGNAME":"varchar(500)",
        "PROD_AI":"varchar(350)",
        "VAL_VBM":"char(1)",
        "ROUTE_":"varchar(40)",
        "DOSE_VBM":"varchar(300)",
        "CUM_DOSE_CHR":"real",
        "CUM_DOSE_UNIT":"char(8)",
        "DECHAL":"char(10)",
        "RECHAL":"char(2)",
        "LOT_NUM":"varchar(400)",
        "EXP_DT":"varchar(150)",
        "NDA_NUM":"varchar(30)",
        "DOSE_AMT":"char(15)",
        "DOSE_UNIT":"char(15)",
        "DOSE_FORM":"varchar(50)",
        "DOSE_FREQ":"char(20)"
    },
    "REAC":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "PT":"varchar(100)",
        "DRUG_REC_ACT":"varchar(70)"
    },
    "OUTC":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "OUTC_COD":"char(2)"
    },
    "RPSR":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "RPSR_COD":"varchar(10)"
    },
    "THER":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "DSG_DRUG_SEQ":"char(15)",
        "START_DT":"char(10)",
        "END_DT":"varchar(10)",
        "DUR":"varchar(10)",
        "DUR_COD":"char(6)",
    },
    "INDI":{
        "PRIMARYID":"int",
        "CASEID":"int",
        "INDI_DRUG_SEQ":"bigint",
        "INDI_PT":"varchar(100)"
    }
}

create_table = "CREATE TABLE {0} ( {1} );"
insert_data = "INSERT INTO {0} ( {1} ) VALUES ( {2} );"
